import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import HeaderTop from './components/HeaderTop'
import HeaderMain from './components/HeaderMain'
import Navbar from './components/Navbar';


//without this slider doesnt show 
//https://github.com/AbdulMoqueet/shopping-web-app/tree/main
//https://www.youtube.com/watch?v=KzqNLDMSdMc
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import MobNavbar from './components/MobNavbar'
import Footer from './components/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <HeaderTop/>
        <HeaderMain/>
        <Navbar/>
        <MobNavbar/>
       
        {children}
        <Footer/></body>
    </html>
  )
}
